{% set version = "2.8.5" %}

package:
  name: expat-split
  version: {{ version }}

source:
  url: url: https://github.com/libexpat/libexpat/releases/download/R_{{ version|replace(".", "_") }}/expat-{{ version }}.tar.xz
  sha256: 1e727b8933ec51a77a9a9d9afcf8e688bce45d907c13e36ab7393fe36e703182

build:
  number: 0

requirements:
  build:
    - cmake-no-system   # [win]
    - make              # [unix]
    - gnuconfig         # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - xmlwf -h

outputs:
  - name: libexpat
    script: {{ "install.bat" if win else "install.sh" }}
    files:
      - lib/libexpat.so.*          # [linux]
      - lib/libexpat.*.dylib       # [osx]
      - Library/bin/libexpat.dll   # [win]
    build:
      ignore_run_exports_from:
        # This package needs the compiler for the tests, but the library
        # does not link to libstdc++.so
        - {{ compiler('cxx') }}
    requirements:
      build:
        - cmake-no-system   # [win]
        - make              # [unix]
        - gnuconfig         # [unix]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
      run:
      run_constrained:
        - expat {{ version }}.*

  - name: expat
    script: {{ "install.bat" if win else "install.sh" }}
    build:
      run_exports:
        # changes soname at major versions, default settings OK
        # https://abi-laboratory.pro/tracker/timeline/expat/
        - {{ pin_subpackage('libexpat') }}
      ignore_run_exports_from:
        # This package needs the compiler for the tests, but the executable
        # does not link to libstdc++.so
        - {{ compiler('cxx') }}
    requirements:
      build:
        - cmake-no-system   # [win]
        - make              # [unix]
        - gnuconfig         # [unix]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('libexpat', exact=True) }}
      run:
        - {{ pin_subpackage('libexpat', exact=True) }}

about:
  home: https://libexpat.github.io
  dev_url: https://github.com/libexpat/libexpat
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C

extra:
  feedstock-name: expat
  recipe-maintainers:
    - danyeaw
    - kwilcox
    - ocefpaf
    - isuruf
    - pelson
    - mingwandroid
    - msarahan
    - scopatz
